# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.

# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    #- go mod tidy
    # you may remove this if you don't need go generate
    #- go generate ./...

# https://goreleaser.com/customization/builds/go/
builds:
  - id: "helloworld" # name of the binary
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: helloworld.go # main entry
    # name of the binary
    # Can be a path (e.g. `bin/app`) to wrap the binary in a directory.
    binary: helloworld
    dir: src # dir of source

# https://goreleaser.com/customization/archive/
archives:
  - id: helloworld # only mandatory is more than one
    formats:
      - tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    # Default: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    name_template: >-
      helloworld_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
